# EmotionMemCore Configuration

# Memory Processing Settings
memory:
  chunk_size: 1000  # 1チャンクあたりの最大文字数
  summary_max_length: 200  # 要約の最大文字数
  emotions_per_memory: 5  # 1つの記憶に付与する最大感情タグ数

# Embedding Settings
embedding:
  model: "text-embedding-3-small"
  dimension: 1536
  batch_size: 100

# LLM Settings
llm:
  claude:
    model: "claude-3-haiku-20240307"
    max_tokens: 500
    temperature: 0.3
  openai:
    model: "gpt-4-turbo-preview"
    max_tokens: 500
    temperature: 0.3

# Search Settings
search:
  default_top_k: 5
  max_top_k: 20
  score_threshold: 0.5

# ChromaDB Settings
chromadb:
  distance_metric: "cosine"
  collection_metadata:
    description: "感情付き記憶データベース"
    version: "1.0.0"

# Debug Settings
debug:
  save_raw_llm_responses: true
  save_processing_time: true
  max_debug_logs: 100

# Cache Settings
cache:
  enable: true
  ttl_seconds: 300  # 5分
  max_size: 1000

# API Settings
api:
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "DELETE"]
    allow_headers: ["*"]
  rate_limit:
    requests_per_minute: 60
    burst_size: 10